on:
    push:
        tags:
            - "v*"

jobs:
    homebrew:
        name: bump-zed-extension
        runs-on: ubuntu-latest
        steps:
            - uses: huacnlee/zed-extension-action@v1.0.0
              with:
                  extension-name: Amber Monochrome Monitor CRT Phosphor Theme
                  extension-path: extensions/${{ amber-monochrome-monitor-crt-phosphor }}
                  push-to: takk8is/zed-extensions
              env:
                  # the personal access token should have "repo" & "workflow" scopes
                  COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
